
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
    # resources/data.yml ?? ??
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create #none #create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      h2:
        console:
          enabled: true
          path: /h2

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    customLoginUrl: /admin/login

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace